### ISSUE TITLE
nrf52840 dongle issue--Nrf Connect does not support 

### ISSUE THREAD

**Issue by dharminec** [makerdiary/nrf52840-mdk-usb-dongle#18]
![image](https://user-images.githubusercontent.com/18609888/74105271-4fef1680-4b2a-11ea-87ab-3f5934a97508.png)

**Comment by caizelin** [comment]
@dharminec The connectivity example in nRF5 SDK does not work with pc-nrfconnect-ble app. You should compile the connectivity firmware from https://github.com/NordicSemiconductor/pc-ble-driver. Because some modifications are needed to patch the connectivity example in nRF5 SDK.

Here are the pre-compiled firmwares you can have a try:
https://github.com/makerdiary/nrf52840-mdk-usb-dongle/tree/master/firmware/ble_connectivity

**Comment by caizelin** [comment]
I’m closing this issue because it has been fixed. Please reopen if you still encounter this issue.
Thank you!
